version: '3.8'
services:

  gateway:
    build: gateway
    image: gateway_image
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server_image
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - shareit_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shareit_db:5432/shareit_db
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  shareit_db:
    image: postgres:14-alpine
    container_name: users_db_container
    environment:
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "6541:5432"